name: NUGET

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack ./PolymorphicTypePropertyGenerator/PolymorphicTypePropertyGenerator.csproj -c Release -p:Version=${{ github.event.release.tag_name }} -o ./out
    - name: Publish
      run: dotnet nuget push ./out/PolymorphicTypePropertyGenerator*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json


